services:
  - type: web
    name: cikaltas
    runtime: php
    region: singapore
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    envVars:
      - key: APP_NAME
        value: CikalTas
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://cikaltas.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
